routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::get('/admin', 'Auth\LoginController@showLoginForm')->name('admin');
Route::get('/admin/download/', 'DownloadController@index')->name('admin.download.index');
Route::get('/admin/download/reload', 'DownloadController@reload')->name('admin.download.reload');

Route::redirect('/home', '/', 301);
// Download
Route::get('/download/{alias}', 'DownloadController@download')->name('download');
//All url served by PagesController
Route::get('/{page?}', 'PagesController@index')->name('pages');

//forms
Route::group(['prefix' => 'mail', 'as' => 'mail.', 'namespace' => 'Mail'], function() {
    Route::post('/subscribe', 'SubscribeController@index')->name('subscribe');
    Route::post('/membership', 'MembershipController@index')->name('membership');
});

// Admin pages
Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin'], function() {
    Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
    Route::resource('/pages', 'PagesController');
    Route::resource('/settings', 'SettingsController');
});

app/Models/Setting.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Setting extends Model
{
	protected $fillable = [
		'key',
		'value',
	];
}

app/Http/Controllers/Admin/SettingsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Setting;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Validation\Rule;
use Illuminate\Support\Facades\Cache;

class SettingsController extends Controller
{

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {

        $this->validate($request, [
            'name' => 'string|max:255|nullable',
            'page' => 'integer',
        ]);

        $name = null;
        if ($request->input('name') && !empty($request->input('name'))) {
            $name = $request->input('name');
        }

        $settings = Setting::when($name !== null, function ($query) use ($name) {
            $query->where('name', $name);
        })
            ->orderBy('id', 'desc')
            ->paginate(50);

        $data = [
            'settings' => []
        ];

        foreach ($settings as $setting) {
            $data['settings'][] = [
                'id'   => $setting['id'],
                'key'   => $setting['key'],
                'value' => \stringFunction::limitText($setting['value'], 40),
            ];
        }

        return view('admin.settings.list', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.settings.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //validation
        $request->validate([
            'key'   => 'required|unique:settings,key|min:2|max:254',
            'value' => 'required'
        ]);

        //store
        Setting::create([
            'key'   => $request->input('key'),
            'value' => $request->input('value')
        ]);

        Cache::forget('settings');

        return response()->redirectToRoute('admin.settings.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return response()->redirectToRoute('admin.settings.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $current = Setting::findOrFail($id);

        return view('admin.settings.edit', compact('current'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //validation
        $request->validate([
            'key'   => ['required', Rule::unique('settings', 'key')->ignore($id), 'min:2', 'max:254'],
            'value' => 'required'
        ]);


        $current = Setting::findOrFail($id);

        //update
        $current->key = $request->input('key');
        $current->value = $request->input('value');

        $current->save();

        Cache::forget('settings');

        return response()->redirectToRoute('admin.settings.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $current = Setting::findOrFail($id);

        $current->delete();

        Cache::forget('settings');

        return response()->redirectToRoute('admin.settings.index');
    }
}

resources/views/admin/settings/create.blade.php
@extends('admin.layouts.main')

@section('content')
    <section>
        <div class="container">
            <h2>{{ __('Add new setting') }}</h2>
            <hr>
            <form action="{{ route('admin.settings.store') }}" method="post">
                {{ csrf_field() }}
                <div class="form-group required">
                    <label for="settingKey">{{ __('Key name') }}</label>
                    <input type="text" class="form-control {{ $errors->first('key') ? "is-invalid" : "" }}"
                           value="{{ old('key') }}" name="key" id="settingKey"
                           placeholder="{{ __('Enter key name') }}">
                    @if($errors->first('key'))
                        <p class="text-danger">{{ $errors->first('key') }}</p>
                    @endif
                </div>
                <div class="form-group required">
                    <label for="settingValue">{{ __('Value') }}</label>
                    <textarea type="text" class="form-control {{ $errors->first('value') ? "is-invalid" : "" }}"
                              rows="4" name="value" id="settingValue"
                              placeholder="{{ __('Enter value') }}">{{ old('value') }}</textarea>
                    @if($errors->first('value'))
                        <p class="text-danger">{{ $errors->first('value') }}</p>
                    @endif
                </div>
                <hr>
                <a href="{{ route('admin.settings.index') }}" class="btn btn-outline-danger">{{ __('Cancel') }}</a>
                <button type="submit" class="btn btn-outline-primary float-right">{{ __('Save') }}</button>
            </form>
        </div>
    </section>
@endsection

resources/views/admin/settings/dashboard.blade.php
@extends('admin.layouts.main')


@section('content')
    <section>
        <div class="container"></div>
    </section>
@endsection

@section('scripts')

@endsection

resources/views/admin/settings/edit.blade.php
@extends('admin.layouts.main')

@section('content')
    <section>
        <div class="container">
            <h2>{{ __('Edit setting') }}</h2>
            <hr>
            <form action="{{ route('admin.settings.update', $current->id) }}" method="post">
                {{ csrf_field() }}
                {{ method_field('PUT') }}
                <div class="form-group required">
                    <label for="settingKey">{{ __('Key name') }}</label>
                    <input type="text" class="form-control {{ $errors->first('key') ? "is-invalid" : "" }}"
                           value="{{ $current->key }}" name="key" id="settingKey"
                           placeholder="{{ __('Enter key name') }}">
                    @if($errors->first('key'))
                        <p class="text-danger">{{ $errors->first('key') }}</p>
                    @endif
                </div>
                <div class="form-group required">
                    <label for="settingValue">{{ __('Value') }}</label>
                    <textarea type="text" class="form-control {{ $errors->first('value') ? "is-invalid" : "" }}"
                              rows="4" name="value" id="settingValue"
                              placeholder="{{ __('Enter value') }}">{{ $current->value }}</textarea>
                    @if($errors->first('value'))
                        <p class="text-danger">{{ $errors->first('value') }}</p>
                    @endif
                </div>
                <hr>
                <a href="{{ route('admin.settings.index') }}" class="btn btn-outline-danger">{{ __('Cancel') }}</a>
                <button type="submit" class="btn btn-outline-primary float-right">{{ __('Save') }}</button>
            </form>
        </div>
    </section>
@endsection

resources/views/admin/settings/list.blade.php
@extends('admin.layouts.main')


@section('content')
    <section>
        <div class="container">
            <div class="buttons float-right mb-2">
                <a href="{{ route('admin.settings.create') }}" class="btn btn-sm btn-success">{{ __('Add new') }}</a>
            </div>
            <table class="table table-hover table-striped table-bordered">
                <thead>
                <tr>
                    <th class="w-50">{{ __('Key') }}</th>
                    <th class="w-25">{{ __('Value') }}</th>
                    <th class="w-25 text-center">{{ __('Actions') }}</th>
                </tr>
                </thead>
                <tbody>
                @foreach($settings as $setting)
                    <tr>
                        <td>{{ $setting['key'] }}</td>
                        <td>
                            {{ $setting['value'] }}
                        </td>
                        <td class="text-center">
                            <a href="{{ route('admin.settings.edit', $setting['id']) }}" class="btn btn-sm btn-warning"
                               title="{{ __('Edit') }}">
                                <i class="fa fa-edit"></i>
                            </a>
                            <button type="submit" form="setting-delete-{{ $setting['id'] }}" class="btn btn-sm btn-danger"
                                    title="{{ __('Delete') }}">
                                <i class="fa fa-times"></i>
                            </button>
                            <form action="{{ route('admin.settings.destroy', $setting['id']) }}" method="POST"
                                  id="setting-delete-{{ $setting['id'] }}">
                                {{ csrf_field() }}
                                {{ method_field('DELETE') }}
                            </form>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </section>
@endsection