routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::get('/admin', 'Auth\LoginController@showLoginForm')->name('admin');
Route::get('/admin/download/', 'DownloadController@index')->name('admin.download.index');
Route::get('/admin/download/reload', 'DownloadController@reload')->name('admin.download.reload');

Route::redirect('/home', '/', 301);
// Download
Route::get('/download/{alias}', 'DownloadController@download')->name('download');
//All url served by PagesController
Route::get('/{page?}', 'PagesController@index')->name('pages');

//forms
Route::group(['prefix' => 'mail', 'as' => 'mail.', 'namespace' => 'Mail'], function() {
    Route::post('/subscribe', 'SubscribeController@index')->name('subscribe');
    Route::post('/membership', 'MembershipController@index')->name('membership');
});

// Admin pages
Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin'], function() {
    Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
    Route::resource('/pages', 'PagesController');
    Route::resource('/settings', 'SettingsController');
});

resources/views/admin/layouts/main.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.googleapis.com">
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/libs.min.css') }}" rel="stylesheet">
    <link href="{{ asset('css/admin.min.css') }}" rel="stylesheet">
    @yield('styles')
</head>
<body>
<div id="app" class="pt-2">
    <nav class="navbar navbar-expand-md navbar-dark bg-dark navbar-laravel fixed-top">
        <div class="container">
            <a class="navbar-brand" href="{{ url('/') }}">
                {{ config('app.name', 'Laravel') }}
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="{{ __('Toggle navigation') }}">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <!-- Left Side Of Navbar -->
                <ul class="navbar-nav mr-auto">

                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="navbar-nav ml-auto">
                    <!-- Authentication Links -->
                    @guest
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                        </li>
                    @else
                        <li class="nav-item {{ Route::currentRouteName() === 'admin.dashboard' ? "active" : '' }}">
                            <a class="nav-link text-uppercase" href="{{ route('admin.dashboard') }}">{{ __('Dashboard') }}</a>
                        </li>
                        <li class="nav-item {{ 0 === stripos(Route::currentRouteName(), 'admin.pages.') ? "active" : '' }}">
                            <a class="nav-link text-uppercase" href="{{ route('admin.pages.index') }}">{{ __('Pages') }}</a>
                        </li>
                        <li class="nav-item {{ 0 === stripos(Route::currentRouteName(), 'admin.download.') ? "active" : '' }}">
                            <a class="nav-link text-uppercase" href="{{ route('admin.download.index') }}">{{ __('Files') }}</a>
                        </li>
                        <li class="nav-item {{ 0 === stripos(Route::currentRouteName(), 'admin.settings.') ? "active" : '' }}">
                            <a class="nav-link text-uppercase" href="{{ route('admin.settings.index') }}">{{ __('Settings') }}</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>

                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                @if (Route::has('register'))
                                    <a class="dropdown-item" href="{{ route('register') }}">{{ __('Register') }}</a>
                                @endif

                                <a class="dropdown-item" href="{{ route('logout') }}"
                                   onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                    {{ __('Logout') }}
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST"
                                      style="display: none;">
                                    @csrf
                                </form>
                            </div>
                        </li>
                    @endguest
                </ul>
            </div>
        </div>
    </nav>

    <main class="py-4 mt-5">
        @yield('content')
    </main>
</div>

<!-- Scripts -->
<script src="{{ asset(mix('js/app.min.js')) }}"></script>
@yield('scripts')
</body>
</html>